== GOST library
:git:               https://git-scm.com[git]
:clojure-deps-cli:  https://clojure.org/guides/getting_started[clojure deps cli]
:tools-build:       https://clojure.org/guides/tools_build[tools-build]
:deps-new:          https://github.com/seancorfield/deps-new[deps-new]
:build-clj:         https://github.com/seancorfield/build-clj[build-clj]
:babashka:          https://github.com/babashka/babashka[babashka]
:toc:

== Intro

This is a thin wrapper for https://bouncycastle.org[Bouncycastle library] to work with GOST algorithms - Russian cryptographic standards.

The library provides:

- encryption, mac using _GOST 28147-89_, _GOST 3412-2015_;
- digest, hmac using _GOST3411-94/2012_ 256 and 512 bits;
- signature with _GOST3410-2001_, _GOST3410-2012_;
- key generation: secret keys, public/private keys, password based keys;
- high level functions:
** compression + encryption + mac / decryption + check mac + decompression
** encrypting with EC public keys / decrypting with EC private keys
** save / load keys (secret, private, public) to file.


This library is successor of https://github.com/middlesphere/crypto-gost[crypto-gost].

== Usage

Add dependency to the `deps.edn`:

[source,clojure]
----
:deps { org.rssys/gost {:mvn/version "0.1.0"}}
----

Require necessary namespaces:

[source,clojure]
----
(require '[org.rssys.gost.encrypt :as e])
----

== Secret key generation

This is high-level functions.

[source, clojure]
----

;; To generate a secret key for the GOST3412-2015 use `generate-secret-key` function.
;; This will return a 256-bit random secret key as a SecretKeySpec object.
;; The algorithm is set to GOST3412-2015
(def secret-key-2015 (e/generate-secret-key))
(e/algo-name secret-key-2015) ;; => GOST3412-2015

;; To generate a secret key GOST28147-89 use `generate-secret-key` function with a parameter.
;; This will return a 256-bit random secret key as a SecretKeySpec object.
;; The algorithm is set to GOST28147.
(def secret-key-89 (e/generate-secret-key e/gost28147))
(e/algo-name secret-key-89) ;; => GOST28147

;; To convert a SecretKeySpec to a byte array:
(e/secret-key->byte-array secret-key-2015) ;; => [B
;; [-38, -86, 71, -42, -69, 73, -33, 53, 72, 80, 38, 26, 57, 69, -114, -1,
;; -119, 13, 113, -84, -31, 54, -128, 114, -79, -55, 85, 126, 105, -96,
;; -37, -128]

;; To convert a byte array to SecretKeySpec:
(e/byte-array->secret-key (byte-array [-38, -86, 71, -42, -69, 73, -33, 53, 72, 80, 38, 26, 57, 69, -114, -1,
                                       -119, 13, 113, -84, -31, 54, -128, 114, -79, -55, 85, 126, 105, -96,
                                       -37, -128])) ;; => #object[javax.crypto.spec.SecretKeySpec

;; We can generate a secret key bytes from a password.
;; This function always return the same bytes value from the same String password.
;; By default, it uses min 10000 iterations of PBKDF2WITHHMACGOST3411 algorithm, recommended by NIST
(e/generate-secret-bytes-from-password "qwerty12345") ;; => [B
;;[-113, 62, 87, -90, 116, -44, -20, -98, 4, -108, 77, -59, -22, 25, -73,
;; 20, -31, 62, -86, 19, 103, 81, -64, 32, 74, 81, -32, -97, -78, 123,
;; -82, -70]

;; To convert it to SecretKeySpec
(e/byte-array->secret-key
  (e/generate-secret-bytes-from-password "qwerty12345")) ;; => #object[javax.crypto.spec.SecretKeySpec

----

== Encryption

This is high-level functions.

[source,clojure]
----
;;;;;;;;;;;;;;;
;; High-level functions
;;;;;;;;;;;;;;;

(def message "This text has length = 32 bytes.")


;; To encrypt a byte array (any binary content) in a most secured way just use `protect-bytes` function.
;; The encryption algorithm GOST3412-2015 or GOST28147-89 is already set in SecretKeySpec.
;; This function calculates Mac for plain data, then
;; compress a plain data to hide information structure, then
;; encrypts data and Mac in CFB mode with always random IV.
;; The encrypted bytes from the same message and same key are always different!
(def encrypted-message (e/protect-bytes secret-key-2015 (.getBytes message))) ;; Returns bytes array with structure:
;; [random(IV), encrypted(Mac), encrypted(compressed-data)]

;; To decrypt and restore a plain text just use `unprotect-bytes` function.
;; The decryption algorithm GOST3412-2015 or GOST28147-89 is already set in SecretKeySpec.
;; This function decrypts Mac and data, then
;; decompress data, then calculate Mac for decompressed data, then
;; compare Mac from a message and Mac calculated.
;; If Macs are the same then return plain data, otherwise throw an Exception.
(def decrypted-message (e/unprotect-bytes secret-key-2015 encrypted-message))

(= message (String. ^bytes decrypted-message)) ;; => true

;; To encrypt a file (any binary content) in a most secured way just use `protect-file` function.
;; The encryption algorithm GOST3412-2015 or GOST28147-89 is already set in SecretKeySpec.
;; This function calculates Mac for plain file, then
;; compress a plain file to hide information structure, then
;; encrypts data and Mac in CFB mode with always random IV.
;; The encrypted bytes from the same message and same key are always different!
(e/protect-file secret-key-2015 "dev/src/examples/plain32.txt" "target/plain32.enc") ;; Encrypted file has structure:
;; random(IV), encrypted(Mac), encrypted(compressed-data).

;; To decrypt a file just use `unprotect-file` function.
;; The decryption algorithm GOST3412-2015 or GOST28147-89 is already set in SecretKeySpec.
;; This function decrypts Mac and data, then
;; decompress data in a file, then calculate Mac for decompressed data, then
;; compare Mac from the message and Mac calculated.
;; If Macs are the same then return output file name as String, otherwise throw an Exception.
(e/unprotect-file secret-key-2015 "target/plain32.enc" "target/plain32.txt")

(= (slurp "dev/src/examples/plain32.txt") (slurp "target/plain32.txt")) ;; => true

----

== Mac generation

This is high-level functions.

[source,clojure]
----
;; To calculate Mac for a file (any binary file) use `mac-stream` function.
;; The encryption algorithm GOST3412-2015 or GOST28147-89 is already set in SecretKeySpec.
;; Mac value from the same data and same SecretKeySpec is always the same.
(e/mac-stream secret-key-2015 "dev/src/examples/plain32.txt") ;; => [B
;; [-111, 125, 10, -34, -109, -109, 41, 115, 81, 61, -90, -80, 16, 71, -108, 91]

;; To calculate Mac for a byte array (any binary file) use the same `mac-stream` function.
;; The encryption algorithm GOST3412-2015 or GOST28147-89 is already set in SecretKeySpec.
;; Mac value from the same data and same SecretKeySpec is always the same.
(e/mac-stream secret-key-2015 (.getBytes message)) ;; => [B
;; [-111, 125, 10, -34, -109, -109, 41, 115, 81, 61, -90, -80, 16, 71, -108, 91]

----

== Some low-level functions

IMPORTANT: Use these functions carefully. If you are not sure use High-level functions only! 

[source,clojure]
----
;; IV length depends on encryption mode and algorithm
(e/iv-length-by-algo-mode e/gost3412-2015 :cfb-mode)        ;; => 16
(e/iv-length-by-algo-mode e/gost3412-2015 :cbc-mode)        ;; => 16
(e/iv-length-by-algo-mode e/gost3412-2015 :ctr-mode)        ;; => 8 !!

(e/iv-length-by-algo-mode e/gost28147 :cfb-mode)        ;; => 8
(e/iv-length-by-algo-mode e/gost28147 :cbc-mode)        ;; => 8
(e/iv-length-by-algo-mode e/gost28147 :ctr-mode)        ;; => 8

;; Mac length
(e/mac-length-by-algo e/gost3412-2015)                      ;; => 16
(e/mac-length-by-algo e/gost28147)                          ;; => 4




----

=== Encryption modes

This is for low-level functions.

Available encryption modes for _GOST3412-2015_:

- `:cfb-mode` is "GOST3412-2015/CFB/NoPadding"
- `:ctr-mode` is "GOST3412-2015/CTR/NoPadding"
- `:cbc-mode` is "GOST3412-2015/CBC/PKCS7Padding"

Available encryption modes for _GOST28147_:

- `:cfb-mode` is "GOST28147/CFB/NoPadding"
- `:ctr-mode` is "GOST28147/CTR/NoPadding"
- `:cbc-mode` is "GOST28147/CBC/PKCS7Padding"

=== Random IV generation

This is low-level functions.

[source,clojure]
----
;; Random IV generation

(e/new-iv-8)                                                ;; => [B
;; [25, 117, -36, -32, -87, -128, -25, 23]

(e/new-iv-16)                                               ;;=> [B
;; [29, -49, 83, 120, -125, 95, 41, -54, -11, -37, -2, -19, 123, -122,
;; -21, 6]

;; Also we can generate IV depend on cipher mode and algorithm name
(e/new-iv e/gost28147 :cfb-mode)                            ;; => [B
;; [-101, 29, 29, 55, 112, 14, 55, 104]

(e/new-iv e/gost3412-2015 :cbc-mode)                        ;; => [B
;; [6, 87, 96, -83, -128, 25, -57, -70, -54, 51, 9, -26, 73, -103, 64, 67]

;; Warning! IV for :ctr-mode is always 8 bytes length for any algorithm
(e/new-iv e/gost3412-2015 :ctr-mode)                        ;; => [B => [45, -71, 116, -67, 9, -39, -101, -51]
(e/new-iv e/gost28147 :ctr-mode)                            ;; => [B => [8, 39, -126, -5, 122, -120, 1, -108]

----


== Build this project

Project org.rssys/gost generated from https://github.com/redstarssystems/libtemplate[Library template].

[#install-prerequisites]
=== Install prerequisites

All these tools you need to install only once.

. Install {clojure-deps-cli} tools version 1.10.3.1069+
.. MacOS
+
[source,bash]
----
brew install clojure/tools/clojure
----
.. Linux
+
Ensure that the following dependencies are installed in OS: `bash`, `curl`, `rlwrap`, and `Java`.
+
[source, bash]
----
curl -O https://download.clojure.org/install/linux-install-1.10.3.1069.sh
chmod +x linux-install-1.10.3.1069.sh
sudo ./linux-install-1.10.3.1069.sh
----

. Install latest {deps-new}
+
[source,bash]
----
clojure -Ttools install io.github.seancorfield/deps-new '{:git/tag "v0.4.9"}' :as new
----
+
Tool will be installed in `~/.gitlibs/libs/`

. Install {babashka} v0.4.0+
.. MacOS
+
[source, bash]
----
brew install borkdude/brew/babashka
----
+
.. Linux
+
[source, bash]
----
sudo bash < <(curl -s https://raw.githubusercontent.com/babashka/babashka/master/install)
----

. Run once:
+
[source,bash]
----
bb requirements
----
to install other necessary tools (MacOS only, for Linux manual instruction).

=== Project workflow

To configure project workflow scripts use `bb.edn` and `build.clj` files.

Run `bb tasks` to show help for project workflow. The following tasks are available:

[source, bash]
----
clean        Clean target folder
build        Build deployable jar file for this project
install      Install deployable jar locally (requires the pom.xml file)
deploy       Deploy this library to Clojars
test         Run tests
repl         Run Clojure repl
outdated     Check for outdated dependencies
outdated:fix Check for outdated dependencies and fix
format       Format source code
lint         Lint source code
requirements Install project requirements
----

== License

Copyright © 2022 Mike Ananev +
Distributed under the Eclipse Public License 1.0 or (at your option) any later version.
